const AR_CONFIG = {
	MINIMUM_INTERACTIVE_ELEMENT_SIZE_PX: 24,
	MINIMUM_TOUCH_TARGET_SPACING_PX: 8,
	CONTRAST_RATIO_AA_NORMAL_TEXT: 4.5,
	CONTRAST_RATIO_AA_LARGE_TEXT: 3,
	CONTRAST_RATIO_AAA_NORMAL_TEXT: 7,
	CONTRAST_RATIO_AAA_LARGE_TEXT: 4.5,
	NON_TEXT_CONTRAST_RATIO_AA: 3,
	LARGE_TEXT_FONT_SIZE_PX: 24,
	LARGE_TEXT_FONT_SIZE_BOLD_PX: 18.66,
	MINIMUM_BODY_TEXT_FONT_SIZE_PX: 13,
	MAX_CHARS_FOR_WALL_OF_TEXT_DETECTION: 600,
	MAX_REPETITIONS_FOR_GENERIC_LINK_TEXT: 2,
	MUTATION_OBSERVER_DEBOUNCE_MILLISECONDS: 750,
	MAX_CHAR_LENGTH_FOR_HEADINGS: 90,
	MIN_CHAR_LENGTH_FOR_NON_EMPTY_ALT_TEXT: 3,
	MAX_SIBLING_SEARCH_DEPTH_FOR_ARIA_RELATIONSHIP: 4,
	MAX_CHAR_LENGTH_FOR_AUTOGENERATED_ARIA_LABEL: 120,
	MIN_CONTRAST_FOR_PDF_ICON: 2.5,
	MIN_CHAR_LENGTH_FOR_REDUNDANT_TITLE_CHECK: 4,
	MAX_WORDS_FROM_CONTEXT_FOR_GENERIC_LINK_ARIA_LABEL: 12,
	ACCESSIBILITY_MENU_BUTTON_ID: 'accessibility-resolver-menu-toggle-button',
	ACCESSIBILITY_MENU_PANEL_ID: 'accessibility-resolver-menu-panel',
	DEFAULT_FONT_SIZE_ADJUSTMENT_INCREMENT: 0.1,
	MAX_FONT_SIZE_ADJUSTMENT_MULTIPLIER: 3,
	MIN_FONT_SIZE_ADJUSTMENT_MULTIPLIER: 0.6,
	READING_MASK_ELEMENT_ID: 'accessibility-resolver-reading-mask',
	READING_LINE_ELEMENT_ID: 'accessibility-resolver-reading-line',
	DYSLEXIA_FRIENDLY_FONT_CLASS_NAME: 'accessibility-resolver-dyslexia-font',
	SATURATION_FILTER_CLASS_NAME: 'accessibility-resolver-saturation-filter',
	TEXT_ALIGNMENT_CLASS_NAME_PREFIX: 'accessibility-resolver-text-align-',
	INCREASED_LETTER_SPACING_CLASS_NAME: 'accessibility-resolver-increased-letter-spacing',
	INCREASED_WORD_SPACING_CLASS_NAME: 'accessibility-resolver-increased-word-spacing',
	INCREASED_LINE_HEIGHT_CLASS_NAME: 'accessibility-resolver-increased-line-height',
	ANIMATIONS_STOPPED_CLASS_NAME: 'accessibility-resolver-animations-stopped',
	HIGHLIGHTED_LINKS_CLASS_NAME: 'accessibility-resolver-highlight-links',
	HIGHLIGHTED_HEADINGS_CLASS_NAME: 'accessibility-resolver-highlight-headings',
	HIGH_CONTRAST_MODE_CLASS_NAME: 'accessibility-resolver-contrast-high',
	INVERTED_CONTRAST_MODE_CLASS_NAME: 'accessibility-resolver-contrast-inverted',
	GRAYSCALE_CONTRAST_MODE_CLASS_NAME: 'accessibility-resolver-contrast-grayscale',
	LOW_SATURATION_CLASS_NAME: 'accessibility-resolver-saturation-low',
	AVATAR_KEYWORDS: [
		'avatar',
		'profile',
		'usericon',
		'dp',
		'user-img',
		'user_image'
	],
	FILENAME_CLEANUP_REGEX: /[-_]/g,
	COMMON_ICON_CLASS_PREFIXES: [
		'fa-',
		'fas',
		'far',
		'fal',
		'fad',
		'fab',
		'glyphicon-',
		'icon-',
		'material-icons',
		'mdi-',
		'bi-',
		'icofont-'
	],
	MENU_ICON_COLOR: '#455a64',
	MENU_ICON_ACTIVE_COLOR: '#ffffff',
	MENU_TEXT_ACTIVE_COLOR: '#ffffff',
	PLACEHOLDER_IMAGE_URL: 'https://placehold.co/{width}x{height}/E0E0E0/BDBDBD?text={text}',
	CONTRAST_ADJUSTMENT_STEPS: 10,
	CONTRAST_ADJUSTMENT_AMOUNT: 0.1,
	AGGRESSIVE_CONTRAST_BG_ADJUST_MAX_DELTA: 0.25
};
const AR_SELECTOR_STRINGS = {
	INTERACTIVE_ELEMENTS: 'button, a[href], input:not([type="hidden"]), select, textarea, [role="button"], [role="link"], [role="checkbox"], [role="radio"], [role="option"], [role="menuitem"], [role="tab"], [role="treeitem"], [role="slider"], [role="spinbutton"], [role="switch"], [tabindex]:not([tabindex="-1"])',
	HEADING_ELEMENTS: 'h1, h2, h3, h4, h5, h6',
	TEXT_CONTAINER_ELEMENTS_AFFECTED_BY_MENU: `p, li, dt, dd, figcaption, blockquote, pre, code, summary, h1, h2, h3, h4, h5, h6, article, section, main, header, footer, nav, aside, div:not(:has(:not(span))):not(#${ AR_CONFIG.ACCESSIBILITY_MENU_PANEL_ID }):not(#${ AR_CONFIG.ACCESSIBILITY_MENU_BUTTON_ID }):not([role="toolbar"]):not([role="menubar"]):not([class*="toast"]):not([class*="modal"]):not([class*="popup"]), span:not(#${ AR_CONFIG.ACCESSIBILITY_MENU_PANEL_ID } *):not(#${ AR_CONFIG.ACCESSIBILITY_MENU_BUTTON_ID } *), td, th, caption, label, legend, em, strong, b, i, small, sub, sup, mark, ins, del, q, cite`.replace(/\s+/g, ' ').trim(),
	FORM_CONTROL_ELEMENTS: 'input:not([type="hidden"]), select, textarea',
	LANDMARK_ROLES_ARRAY: [
		'main',
		'banner',
		'contentinfo',
		'navigation',
		'complementary',
		'form',
		'region',
		'search'
	],
	LANDMARK_HTML_TAGS_ARRAY: [
		'main',
		'header',
		'footer',
		'nav',
		'aside',
		'form',
		'section'
	],
	MEDIA_ELEMENTS: 'img, svg, canvas, iframe, audio, video',
	MAIN_CONTENT_TARGET_SELECTORS: 'main, [role="main"], #main, #content, .main, .page-content, article, #main-content, [data-main-content], .container, .wrapper, #page-wrapper, div[class*="content-area" i], section[class*="main-content" i]',
	NATIVE_INTERACTIVE_TAGS: 'button, a, input, select, textarea',
	COMMON_HEADER_SELECTORS: 'body > header, body > div[id*="header" i], body > div[class*="header" i], body > div[id*="banner" i], body > div[class*="banner" i], body > .site-header, body > #site-header, body > #masthead',
	COMMON_FOOTER_SELECTORS: 'body > footer, body > div[id*="footer" i], body > div[class*="footer" i], body > div[id*="colophon" i], body > .site-footer, body > #site-footer',
	COMMON_NAV_SELECTORS: 'body > nav, body > div[id*="nav" i], body > div[class*="nav" i], body > ul[class*="nav" i], body > div[id*="menu" i], body > ul[id*="menu" i], body > .main-nav, body > #main-nav, body > .primary-navigation'
};
let ar_accessibilityIssuesLog = [];
let ar_totalScannedIssuesCounter = 0;
let ar_totalAutoFixedIssuesCounter = 0;
const ar_generatedUniqueElementIds = new Set();
const ar_detectedLandmarkRoleCounts = {};
let ar_mainMutationObserverDebounceTimeout;
const ar_originalElementStylesMap = new Map();
let ar_activeReadingGuideType = null;
const ar_loggedIssuesTracker = new Set()
